### ISSUE TITLE
Comments please

### ISSUE THREAD

**Issue by lairdm** [ga4gh/gsoc2018-ref-retrieval-api#2]
@someshchaturvedi I just looked at mockserver.py, I'm getting a little tough right now, I'm not going to read through it in it's current state. It looks clean and nice, but there are no comments. Please go through the repo and comment your code, it might be simple enough what you're doing but someone reviewing it shouldn't have to think too hard in figuring out the basic flow.

Thanks.

**Comment by someshchaturvedi** [comment]
I've added the comments in `mockserver.py` .Shall I close this issue?
