### ISSUE TITLE
utf-8?

### ISSUE THREAD

**Issue by lairdm** [ga4gh/gsoc2018-ref-retrieval-api#3]
https://github.com/ga4gh/gsoc2018-ref-retrieval-api/blob/3213960002ec4e8367d9ac4661d64b9bbb9c2172/test_suite/mockserver.py#L212

All these lines with send utf-8, are you sure you want to do that? We need ASCII encoding for sequence data according to the spec. Please correct me if I'm misunderstanding something.

**Comment by someshchaturvedi** [comment]
Sorry. There was some confusion. I've fixed the issue. Thanks.
