### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by lairdm** [ga4gh/gsoc2018-ref-retrieval-api#4]
https://github.com/ga4gh/gsoc2018-ref-retrieval-api/blob/3213960002ec4e8367d9ac4661d64b9bbb9c2172/test_suite/test_sequence_success.py#L4

This code will hopefully live for many years. Could you please flesh out the documentation a bit in these files, for example, how this file works, a little blurb about the structure of these functions and what they're for in the testing framework. I know it's pretty obvious, but better to err on the side of completeness. Thanks.

**Comment by someshchaturvedi** [comment]
I've added appropriate comments in the files. Thanks.
