### ISSUE TITLE
Relative paths

### ISSUE THREAD

**Issue by lairdm** [ga4gh/gsoc2018-ref-retrieval-api#5]
https://github.com/ga4gh/gsoc2018-ref-retrieval-api/blob/c57cf5a5603f1541890981c270a7c379064bc8de/test_suite/utils.py#L17

This is dangerous depending where the script is run from.

It'd be far better to do something like os.path.abspath(__FILE__), then build the relative path off of what you receive back from that. There's functionality in os.path to build a path, concatenating pieces, in an OS safe manner.

**Comment by someshchaturvedi** [comment]
Check out commit https://github.com/ga4gh/gsoc2018-ref-retrieval-api/commit/1a3bb8bb845c3f79e5f5f93fa4b88d0c7f0a2e36 . Thanks.
