### ISSUE TITLE
text/plain

### ISSUE THREAD

**Issue by lairdm** [ga4gh/gsoc2018-ref-retrieval-api#6]
https://github.com/ga4gh/gsoc2018-ref-retrieval-api/blob/99c7977684d570a1b3570124b839a41fdf8de5e2/test_suite/mockserver.py#L221

You might want to add text/plain, since it's an alias for our custom encoding.

**Comment by someshchaturvedi** [comment]
Done. Do you want me to add a sample query with 'text/plain 'in docs too?
